### PR TITLE
expand tests with various invalid json

### PR DESCRIPTION
**Pull request by jpmikkers**
Added:
- tests for malformed json
- added sanity check for json with insanely large token gaps (otherwise some malformed json could eat up all of the memory)
- rewrite of the parsing loop

### CODE REVIEW

**Comment by Mimetis** [comment]
The parsing loop is way much more simpler.
It took me quite some time to figure it out, but I think this refactoring is worth it.
Thanks for your hard work and contributions to this small json extensions helpers

I've some idea to add features, and I will add them based on your refactoring.

**Comment by jpmikkers** [comment]
@Mimetis I've also been trying to improve the Number type determination but so far the solutions are not very pretty and/or slow 🤷

**Comment by Mimetis** [comment]
I'm currently working on a different way to get values.
The problem is that we can't stop / move / skip during iteration

I would like to rename the `Read()` method to `Values()` and introduce a `Read()` method that will return true / false and a property `Current` to get the current retrieved value.

``` cs 
while (jsonReader.Read())
{
    
    if (jsonReader.Current.TokenType == JsonTokenType.PropertyName)
    {
        var prop = jsonReader.Current.Name;
        jsonReader.Skip();
        var value = jsonReader.Current.Value;
        Console.WriteLine($"{prop}: {value}");
    }
}
```
But I still want to be able to iterate, of course:

``` cs
foreach (var prop in jsonReader.Values())
{

}
```

Having an instance with a "state" will also allow us to reuse the same instance in multiple places:
``` cs
while (jsonReader.Read() && jsonReader.Current.PropertyName != "A")
{
 .. // DO stuff
}

.... // Do stuff

// continue to iterate
jsonReader.Read();

``` 


But doing this will introduce some state variables and will need to implement IDisposable.

I'm currently on it, and will make a first draft PR, to see if it's viable.

**Comment by Mimetis** [comment]
> @Mimetis I've also been trying to improve the Number type determination but so far the solutions are not very pretty and/or slow 🤷

The only thing I found so far, that is pretty slow, unfortunately :

``` cs
    private static object? GetNumber(ref Utf8JsonReader reader)
    {
        if (reader.TryGetInt16(out short shortValue))
            return shortValue;
        if (reader.TryGetInt32(out int intValue))
            return intValue;
        if (reader.TryGetInt64(out long longValue))
            return longValue;
        if (reader.TryGetDouble(out double doubleValue))
            return doubleValue;
        return null;
    }
```

**Comment by jpmikkers** [comment]
Exactly that, but there's a weird thing about trygetdouble, if the number is too big it doesn't return false, it will give you a + or - infinity.

**Comment by jpmikkers** [comment]
Hmm for integers it would be faster to do trygetint64 and then cast to int32 or int16 if the value allows it.

**Pull request merged**
